T2-Papillon/Spring

- papplan/.idea/.gitignore
- papplan/.idea/compiler.xml
- papplan/.idea/encodings.xml
- papplan/.idea/jarRepositories.xml
- papplan/.idea/misc.xml
- papplan/.idea/modules.xml
- papplan/.idea/remote-targets.xml
- papplan/.idea/uiDesigner.xml
- papplan/.idea/vcs.xml
- papplan/papplan.iml
- papplan/pom.xml
- papplan/src/main/java/com/boogle/papplan/entity/Contributor.java
- papplan/src/main/java/com/boogle/papplan/entity/Employees.java
- papplan/src/main/java/com/boogle/papplan/entity/Project.java
- papplan/src/main/java/com/boogle/papplan/entity/ProjectPriority.java
- papplan/src/main/java/com/boogle/papplan/entity/ProjectPriorityEntity.java
- papplan/src/main/java/com/boogle/papplan/entity/ProjectStatus.java
- papplan/src/main/java/com/boogle/papplan/entity/ProjectStatusEntity.java
- papplan/src/main/java/com/boogle/papplan/entity/project.java
브랜치 전략에 따라 통일된 방식 사용을 위해 브랜치 명을 entity v0.1.0/dana 로 변경하였습니다
> entity v0.1.0/dana 브랜치명 변경

- papplan/.idea/.gitignore
- papplan/.idea/compiler.xml
- papplan/.idea/encodings.xml
- papplan/.idea/jarRepositories.xml
- papplan/.idea/misc.xml
- papplan/.idea/modules.xml
- papplan/.idea/remote-targets.xml
- papplan/.idea/vcs.xml
- papplan/papplan.iml
- papplan/pom.xml
- papplan/src/main/java/com/boogle/papplan/entity/project.java
각 팀원의 브랜치를 main 브랜치에 병합하기 전에 변경 사항에 대한 테스트와 검증을 위해 dev 브랜치를 생성했습니다
> dev 브랜치 생성

- papplan/src/main/java/com/boogle/papplan/controller/ProjectListController.java
- papplan/src/main/java/com/boogle/papplan/entity/ProjectStatus.java
- papplan/src/main/java/com/boogle/papplan/repository/ContributorRepository.java
- papplan/src/main/java/com/boogle/papplan/repository/ProjectListRepository.java
- papplan/src/main/java/com/boogle/papplan/service/ProjectListService.java
어떤 변경 사항이 있나요?
[ADD] 프로젝트 목록
[MOD] ProjectStatus 작성법 변경
> ProjectList_v0.1.0/dana

- papplan/src/main/java/com/boogle/papplan/controller/SearchController.java
- papplan/src/main/java/com/boogle/papplan/repository/SearchRepository.java
- papplan/src/main/java/com/boogle/papplan/repository/TotalSearchRepository.java
- papplan/src/main/java/com/boogle/papplan/service/SearchService.java
- papplan/src/main/java/com/boogle/papplan/service/SearchServiceImpl.java
어떤 변경 사항이 있나요?
[ADD] 통합 검색 페이지 추가
> [ADD] 통합검색 페이지

- papplan/src/main/java/com/boogle/papplan/controller/StatisticController.java
- papplan/src/main/java/com/boogle/papplan/dto/StatisticTaskStatusDto.java
- papplan/src/main/java/com/boogle/papplan/repository/StatisticRepository.java
- papplan/src/main/java/com/boogle/papplan/service/StatisticService.java
어떤 변경 사항이 있나요?
[ADD] 프로젝트 통계분석 추가
- 추가항목 : 특정 프로젝트의 업무들에 대해 각 진행 상태별로 업무가 몇 개씩 있는지 조회
> [ADD] Project Statistics(2)

- papplan/src/main/java/com/boogle/papplan/controller/SearchController.java
- papplan/src/main/java/com/boogle/papplan/repository/SearchRepository.java
- papplan/src/main/java/com/boogle/papplan/service/SearchService.java
어떤 변경 사항이 있나요?
통합검색 페이지에서 전체 프로젝트 목록을 진행상태별로 필터링 해주고 프로젝트명/PM/참여자로 프로젝트 검색하는 기능 수정, swagger 통해 정상 작동 확인
> [MOD] 오류로 인한 통합 검색 페이지 수정

- papplan/src/main/java/com/boogle/papplan/controller/ProjectController.java
- papplan/src/main/java/com/boogle/papplan/controller/SearchController.java
- papplan/src/main/java/com/boogle/papplan/controller/TaskController.java
- papplan/src/main/java/com/boogle/papplan/service/ProjectService.java
어떤 변경 사항이 있나요?
1. ProjectController/TaskController api 링크 변경 
2. SearchController에 프론트엔드 관련 @crossorigin 어노테이션 추가
3. 로그인한 사용자의 프로젝트 목록 조회 기능 추가
> [MOD] 프로젝트 목록_ 다양한 기능 수정

- papplan/src/main/java/com/boogle/papplan/controller/SearchController.java
- papplan/src/main/java/com/boogle/papplan/dto/ProjectDto.java
- papplan/src/main/java/com/boogle/papplan/entity/ProjectPriority.java
- papplan/src/main/java/com/boogle/papplan/service/SearchService.java
어떤 변경 사항이 있나요?
1. json 파싱 오류로 데이터 순환 반복 문제를 해결하기 위해 Search 관련 Dto 추가 및 코드 수정 완료 후 json 파싱 오류 해결 확인!
2. ProjectPriority 엔티티에서 속성이 스네이크 기법으로 설정되어 있는 것을 발견하여 카멜 기법으로 수정 완료
> [ADD] json 파싱 오류로 데이터 순환 반복 문제를 해결하기 위해 Dto 추가 진행

- papplan/src/main/java/com/boogle/papplan/controller/ProjectController.java
- papplan/src/main/java/com/boogle/papplan/dto/ProjectDto.java
- papplan/src/main/java/com/boogle/papplan/entity/Project.java
- papplan/src/main/java/com/boogle/papplan/service/ProjectService.java
- papplan/src/main/java/com/boogle/papplan/service/SearchService.java
어떤 변경 사항이 있나요?
json 파싱 오류로 데이터 순환 반복 문제를 해결하기 위해 Search 관련 Dto 추가 및 코드 수정 완료 후 json 파싱 오류 해결 확인!
> [ADD] 통합검색페이지_json 파싱 오류로 데이터 순환 반복 문제 해결 위한 Dto 추가

- papplan/src/main/java/com/boogle/papplan/controller/TaskController.java
어떤 변경 사항이 있나요?
taskId -> taskNo 로 명칭 수정
> [MOD] Project 수정

- papplan/src/main/java/com/boogle/papplan/controller/ProjectController.java
어떤 변경 사항이 있나요?
ProjectController에서 @RequestParam 으로 통일 작업 진행
> [MOD] ProjectController에서 @RequestParam 으로 통일 작업 진행

- papplan/src/main/java/com/boogle/papplan/controller/ProjectController.java
- papplan/src/main/java/com/boogle/papplan/service/project/ProjectService.java
- papplan/src/main/java/com/boogle/papplan/service/project/ProjectServiceImpl.java
어떤 변경 사항이 있나요?
ProjectServiceImpl을 생성하여 ProjectService 코드 분할 진행 완료
> [MOD] ProjectServiceImpl 생성하여 코드 분할 진행

- papplan/src/main/java/com/boogle/papplan/config/WebConfig.java
- papplan/src/main/java/com/boogle/papplan/controller/LoginController.java
- papplan/src/main/java/com/boogle/papplan/service/employee/EmployeeService.java
- papplan/src/main/java/com/boogle/papplan/service/employee/EmployeeServiceImpl.java
어떤 변경 사항이 있나요?
- 로그인 응답으로 사용자 정보 response 추가
- CORS WebConfig 추가
> [FIX] 로그인 API 수정

- papplan/src/main/java/com/boogle/papplan/controller/ProjectController.java
- papplan/src/main/java/com/boogle/papplan/controller/SearchController.java
- papplan/src/main/java/com/boogle/papplan/dto/EmployeeDTO.java
- papplan/src/main/java/com/boogle/papplan/dto/project/ProjectDTO.java
- papplan/src/main/java/com/boogle/papplan/dto/project/ProjectQueryDTO.java
- papplan/src/main/java/com/boogle/papplan/repository/EmployeeRepository.java
- papplan/src/main/java/com/boogle/papplan/repository/ProjectRepository.java
- papplan/src/main/java/com/boogle/papplan/service/project/ProjectService.java
- papplan/src/main/java/com/boogle/papplan/service/project/ProjectServiceImpl.java
- papplan/src/main/java/com/boogle/papplan/service/search/SearchService.java
- papplan/src/main/java/com/boogle/papplan/service/search/SearchServiceImpl.java
- papplan/src/main/resources/application-local.yml
어떤 변경 사항이 있나요?
- ProjectController, SearchController 프로젝트 조회 시 결과에 참여자 정보 나오도록 추가
- 하나의 쿼리로 조회해보려 했으나 1차 실패
- 추후 대용량 데이터 처리 시 재시도 예정
- 추가 DTO 생성에 따른 Project DTO 디렉토리 추가
> [ADD] 프로젝트 조회 시 참여자 정보 추가

- papplan/src/main/java/com/boogle/papplan/controller/TaskController.java
- papplan/src/main/java/com/boogle/papplan/repository/TaskRepository.java
- papplan/src/main/java/com/boogle/papplan/service/task/TaskServiceImpl.java
task serviceImpl update 부분 작업
- controller put -> post 로 바꾸끼
- update 기능 추가
> [ADD] Task Update serviceImpl 

- papplan/src/main/java/com/boogle/papplan/controller/LoginController.java
- papplan/src/main/java/com/boogle/papplan/controller/ProjectController.java
- papplan/src/main/java/com/boogle/papplan/controller/TaskController.java
- papplan/src/main/java/com/boogle/papplan/service/task/TaskService.java
- papplan/src/main/java/com/boogle/papplan/service/task/TaskServiceImpl.java
마이페이지 구현 시 전체 task를 조회하는 api가 필요해서 추가했습니다.
> [ADD]전체Task조회 추가

- papplan/src/main/java/com/boogle/papplan/controller/TaskController.java
- papplan/src/main/java/com/boogle/papplan/service/task/TaskService.java
- papplan/src/main/java/com/boogle/papplan/service/task/TaskServiceImpl.java
> Revert "[ADD]전체Task조회 추가"

- papplan/src/main/java/com/boogle/papplan/controller/TaskController.java
- papplan/src/main/java/com/boogle/papplan/repository/TaskRepository.java
- papplan/src/main/java/com/boogle/papplan/service/task/TaskService.java
- papplan/src/main/java/com/boogle/papplan/service/task/TaskServiceImpl.java
어떤 변경 사항이 있나요?
프로젝트 내 하위업무 검색 기능 추가
> [ADD] 프로젝트 내 하위업무 검색 기능 추가

- papplan/src/main/java/com/boogle/papplan/config/SpringConfig.java
- papplan/src/main/java/com/boogle/papplan/config/WebConfig.java
어떤 변경 사항이 있나요?
- CORS 필터 적용
- 테스트 목적으로 모든 host 허용
> [ADD] CORS filter

- papplan/src/main/java/com/boogle/papplan/controller/TaskController.java
- papplan/src/main/java/com/boogle/papplan/repository/TaskRepository.java
- papplan/src/main/java/com/boogle/papplan/service/task/TaskService.java
- papplan/src/main/java/com/boogle/papplan/service/task/TaskServiceImpl.java
어떤 변경 사항이 있나요?
- 특정 프로젝트 내 하위업무를 진행상태별로 조회할 수 있는 기능 추가
> [ADD] 특정 프로젝트 내 하위업무를 진행상태별로 조회할 수 있는 기능 추가

- papplan/src/test/java/com/boogle/papplan/service/project/ProjectServiceImplTest.java
- papplan/src/test/java/com/boogle/papplan/service/search/SearchServiceImplTest.java
어떤 변경 사항이 있나요?
1. 로그인한 사용자가 참여하는 프로젝트 검색 기능 테스트 코드 작성
2. 전체 프로젝트(로그인한 사용자 상관없이) 검색 기능 테스트 코드 수정
> [ADD] 프로젝트목록P_로그인한 사용자가 참여하는 프로젝트 검색 테스트 코드 작성

- papplan/src/main/java/com/boogle/papplan/controller/DashBoardController.java
- papplan/src/main/java/com/boogle/papplan/repository/TaskRepository.java
- papplan/src/main/java/com/boogle/papplan/service/task/TaskService.java
- papplan/src/main/java/com/boogle/papplan/service/task/TaskServiceImpl.java
- papplan/src/main/java/com/boogle/papplan/util/DashBoardDataUtil.java
> [ADD] DashBoard API 건수 데이터 추가

- papplan/src/main/java/com/boogle/papplan/controller/TaskController.java
- papplan/src/test/java/com/boogle/papplan/service/project/ProjectServiceImplTest.java
> [Feat] 진도율 반영

- papplan/src/main/java/com/boogle/papplan/dto/TaskDTO.java
- papplan/src/main/java/com/boogle/papplan/entity/Task.java
- papplan/src/main/java/com/boogle/papplan/repository/TaskRepository.java
- papplan/src/main/java/com/boogle/papplan/service/task/TaskServiceImpl.java
어떤 변경 사항이 있나요?
하위업무 데이터를 이름이 아닌 eno로 받아오도록 변경
> [MOD] 하위업무 데이터를 이름이 아닌 eno로 받아오도록 변경

- papplan/src/main/java/com/boogle/papplan/dto/TaskDTO.java
- papplan/src/main/java/com/boogle/papplan/service/task/TaskServiceImpl.java
어떤 변경 사항이 있나요?
- TaskDTO에 Assignee의 이름과 사번 추가
> [MOD] TaskDTO에 Assignee의 이름과 사번 추가

- papplan/src/main/java/com/boogle/papplan/service/task/TaskServiceImpl.java
어떤 변경 사항이 있나요?
- Assignee의 부서 관련해서 가지고올 데이터를 dept_name이 아닌 dept_no로 변경
> [MOD] Assignee의 부서명 관련 코드 수정

- papplan/src/main/java/com/boogle/papplan/controller/DashBoardController.java
- papplan/src/main/java/com/boogle/papplan/dto/project/ProjectDTO.java
- papplan/src/main/java/com/boogle/papplan/service/project/ProjectService.java
- papplan/src/main/java/com/boogle/papplan/service/project/ProjectServiceImpl.java
- papplan/src/main/java/com/boogle/papplan/service/task/TaskService.java
- papplan/src/main/java/com/boogle/papplan/service/task/TaskServiceImpl.java
- papplan/src/main/java/com/boogle/papplan/util/DashBoardDataUtil.java
> [MOD] PM DTO 수정

- papplan/src/main/java/com/boogle/papplan/service/project/ProjectServiceImpl.java
> [FIX] DTO Format

- papplan/src/main/java/com/boogle/papplan/repository/ProjectRepository.java
- papplan/src/main/java/com/boogle/papplan/service/search/SearchServiceImpl.java
- papplan/src/test/java/com/boogle/papplan/service/search/SearchServiceImplTest.java
어떤 변경 사항이 있나요?
- 통합검색 서비스 테스트 진행상태값 관련 코드 추가
- 진행상태값 예외처리 관련 코드 레포지토리와 서비스에 추가
> [ADD] 통합검색 서비스 테스트 코드 추가 및 진행상태값 예외처리 추가

- papplan/src/test/java/com/boogle/papplan/service/search/SearchControllerTest.java
어떤 변경 사항이 있나요?
- 유효한 진행상태값 입력했을 때의 테스트 코드 작성
> [ADD] SearchControllerTest 작업

- papplan/src/main/java/com/boogle/papplan/controller/TaskController.java
- papplan/src/main/java/com/boogle/papplan/service/task/TaskService.java
- papplan/src/main/java/com/boogle/papplan/service/task/TaskServiceImpl.java
> [ADD] 사원번호로 하위업무 조회 API 추가

- papplan/src/main/java/com/boogle/papplan/controller/ProjectController.java
- papplan/src/main/java/com/boogle/papplan/repository/EmployeeRepository.java
- papplan/src/main/java/com/boogle/papplan/repository/ProjectPriorityRepository.java
- papplan/src/main/java/com/boogle/papplan/repository/ProjectStatusRepository.java
- papplan/src/main/java/com/boogle/papplan/service/project/ProjectService.java
- papplan/src/main/java/com/boogle/papplan/service/project/ProjectServiceImpl.java
어떤 변경 사항이 있나요?
- 프로젝트 생성 관련 코드 수정
- 프로젝트 생성 api 추가
> [ADD] 프로젝트 생성 api 추가

- papplan/src/main/java/com/boogle/papplan/controller/MyPageController.java
> [ADD] MypageController 추가

- papplan/src/main/java/com/boogle/papplan/dto/project/ProjectCreateDTO.java
- papplan/src/main/java/com/boogle/papplan/dto/project/ProjectDTO.java
- papplan/src/main/java/com/boogle/papplan/service/project/ProjectServiceImpl.java
> [MOD] Projcet DTO 수정

- papplan/src/main/java/com/boogle/papplan/controller/LoginController.java
- papplan/src/main/java/com/boogle/papplan/controller/ProjectController.java
- papplan/src/main/java/com/boogle/papplan/controller/SearchController.java
- papplan/src/main/java/com/boogle/papplan/dto/employee/EmpSearchDTO.java
- papplan/src/main/java/com/boogle/papplan/dto/employee/EmployeeDTO.java
- papplan/src/main/java/com/boogle/papplan/dto/project/ProjectCreateDTO.java
- papplan/src/main/java/com/boogle/papplan/dto/project/ProjectDTO.java
- papplan/src/main/java/com/boogle/papplan/repository/EmployeeRepository.java
- papplan/src/main/java/com/boogle/papplan/service/employee/EmployeeService.java
- papplan/src/main/java/com/boogle/papplan/service/employee/EmployeeServiceImpl.java
- papplan/src/main/java/com/boogle/papplan/service/project/ProjectServiceImpl.java
- papplan/src/main/java/com/boogle/papplan/service/search/SearchService.java
- papplan/src/main/java/com/boogle/papplan/service/search/SearchServiceImpl.java
> [ADD] Employee 검색 API

- papplan/src/main/java/com/boogle/papplan/service/project/ProjectServiceImpl.java
- papplan/src/main/java/com/boogle/papplan/service/search/SearchServiceImpl.java
> [MOD] SearchService 쿼리 최적화 수정

- .github/workflows/action-dev.yml
> [MOD] 최종 main branch merge

- papplan/src/main/java/com/boogle/papplan/controller/LoginController.java
- papplan/src/main/java/com/boogle/papplan/controller/TaskController.java
- papplan/src/main/java/com/boogle/papplan/util/DashBoardDataUtil.java
> [MOD] 전일 집계 오류 수정 

- README.md
- papplan/pom.xml
> Final Deploy

- papplan/docker-compose.yml
> [ADD] Docker timezone

- papplan/src/main/java/com/boogle/papplan/util/DashBoardDataUtil.java
> [MOD] timezone 로직 수정
